### ISSUE TITLE
pip not using 3.5 by default

### ISSUE THREAD

**Issue by clayball** [wharton/python-vagrant-centos7#2]
```pip install django-extensions pygraphviz```

Produces the following exception:

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 326, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 834, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1037, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/django_extensions'
```

Python 2.7 is being referenced. 

I'll update the README file.

Not sure if making changes to the Vagrantfile or wherever would provide a fix for this or not.

**Comment by FlipperPA** [comment]
Hi Clay,

The system `pip` runs against Python 2.7.5 by default. However, when you fire up a virtualenv, it will use the proper Python version (3.5) and pip (3.5) by default. Please let me know if this isn't the case; I clarified the documentation. Thanks!
